name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker build -t build .
          docker run --name build build
          docker cp build:/build/target/doc ./doc
      - uses: actions/upload-artifact@v4
        with:
          path: ./doc